#!/usr/bin/env php
<?php

if (isset($argv[1])) {
	if (file_exists($argv[1]) 
		&& (strpos($argv[1], '.php') 
			|| strpos($argv[1], '.json'))) {
		
		if (strpos($argv[1], '..') !== false) {
			echo "Nope!\r\n";
		}

		$questions = [];		

		if (strpos($argv[1], '.php')) {
			$questions = include $argv[1];
		} else if (strpos($argv[1], '.json')) {
			$json = file_get_contents($argv[1]);
			$questions = json_decode($json, 1);
		}

		if (count($questions) > 0) {
			
			$Exam = new \Flashcards\Exam($questions);
			$Exam->present();

		} else {
			echo "No questions provided\r\n";
		}
	} else {
		echo "Invalid question file.\r\n";
	}
} else {
	echo "No questions provided.\r\n";
}
