#!/usr/bin/env php
<?php

if (isset($argv[1])) {
	if(file_exists($argv[1]) 
		&& (strpos($argv[1], '.php') 
			|| strpos($argv[1], '.json'))) {
		if (strpos($argv[1], '..') !== false) {
			echo "Nope!\r\n";
		}	
	} else {
		echo "Invalid question file\r\n";
	}
} else {
	echo "No questions provided.\r\n";
}
